name: Build Free iOS IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Unsigned iOS Archive
        run: flutter build ios --release --no-codesign
      - name: Package Into IPA
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: free-ios-app
          path: app.ipa
